[default]
description = "Default permissions for the plugin"
permissions = [
  "allow-exit-app",
  "allow-return-to-home",
  "allow-set-status-bar",
  "allow-hide-status-bar",
  "allow-get-system-font-scale",
  "allow-get-screen-orientation",
  "allow-set-screen-orientation",
  "allow-get-brightness",
  "allow-get-system-brightness",
  "allow-set-brightness",
  "allow-get-volume",
  "allow-set-volume",
  "allow-get-device-id",
  "allow-register-listener",
  "allow-remove-listener",
  "allow-check-permissions",
  "allow-request-permissions",
]
